name: rag_auto
channels:
  - pytorch
  - nvidia
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - certifi=2023.11.17
  - charset-normalizer=2.0.4
  - comm=0.1.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.0.4
  - executing=0.8.3
  - ffmpeg=4.3
  - filelock=3.13.1
  - freetype=2.12.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - idna=3.4
  - intel-openmp=2023.1.0
  - ipykernel=6.25.0
  - ipython=8.15.0
  - jedi=0.18.1
  - jinja2=3.1.3
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - lame=3.100
  - lcms2=2.12
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libiconv=1.16
  - libidn2=2.3.4
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.7.3
  - networkx=3.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.12
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=23.3.1
  - platformdirs=3.10.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.8.2
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pyzmq=25.1.0
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - sympy=1.12
  - tbb=2021.8.0
  - tk=8.6.12
  - torchaudio=2.0.2
  - torchvision=0.15.2
  - tornado=6.3.3
  - traitlets=5.7.1
  - typing_extensions=4.9.0
  - urllib3=2.1.0
  - wheel=0.41.2
  - xz=5.4.6
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - aiofiles==23.2.1
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - altair==5.2.0
      - annotated-types==0.6.0
      - anyio==4.3.0
      - async-timeout==4.0.3
      - attrs==23.2.0
      - beautifulsoup4==4.12.3
      - clean-text==0.6.0
      - click==8.1.7
      - colorama==0.4.6
      - contourpy==1.2.0
      - cycler==0.12.1
      - dataclasses-json==0.6.4
      - distro==1.9.0
      - emoji==1.7.0
      - faiss-cpu==1.8.0
      - fastapi==0.110.0
      - ffmpy==0.3.2
      - fonttools==4.49.0
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - ftfy==6.1.3
      - gradio==4.21.0
      - gradio-client==0.12.0
      - greenlet==3.0.3
      - h11==0.14.0
      - httpcore==1.0.4
      - httpx==0.27.0
      - huggingface-hub==0.21.4
      - importlib-resources==6.3.0
      - joblib==1.3.2
      - jsonpatch==1.33
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - langchain==0.1.11
      - langchain-community==0.0.25
      - langchain-core==0.1.29
      - langchain-openai==0.0.8
      - langchain-text-splitters==0.0.1
      - langchainhub==0.1.15
      - langserve==0.0.46
      - langsmith==0.1.21
      - lxml==5.1.0
      - markdown-it-py==3.0.0
      - marshmallow==3.21.1
      - matplotlib==3.8.3
      - mdurl==0.1.2
      - multidict==6.0.5
      - mypy-extensions==1.0.0
      - nltk==3.8.1
      - openai==1.13.3
      - orjson==3.9.15
      - packaging==23.2
      - pandas==2.2.1
      - pydantic==2.6.3
      - pydantic-core==2.16.3
      - pydub==0.25.1
      - pyparsing==3.1.2
      - python-multipart==0.0.9
      - pytz==2024.1
      - pyyaml==6.0.1
      - referencing==0.33.0
      - regex==2023.12.25
      - rich==13.7.1
      - rpds-py==0.18.0
      - ruff==0.3.2
      - safetensors==0.4.2
      - scikit-learn==1.4.1.post1
      - scipy==1.12.0
      - semantic-version==2.10.0
      - sentence-transformers==2.5.1
      - shellingham==1.5.4
      - sniffio==1.3.1
      - soupsieve==2.5
      - sqlalchemy==2.0.28
      - starlette==0.36.3
      - tenacity==8.2.3
      - threadpoolctl==3.3.0
      - tiktoken==0.6.0
      - tokenizers==0.15.2
      - tomlkit==0.12.0
      - toolz==0.12.1
      - tqdm==4.66.2
      - transformers==4.38.2
      - typer==0.9.0
      - types-requests==2.31.0.20240310
      - typing-inspect==0.9.0
      - tzdata==2024.1
      - uvicorn==0.28.0
      - wcwidth==0.2.13
      - websockets==11.0.3
      - yarl==1.9.4
